version: '3.5'

services:
  frontend:
    image: node:latest
    command: bash -c 'cd /frontend; yarn; yarn start'
    volumes:
      - ./frontend:/frontend

  nginx:
    build:
      context: ./nginx
      args:
        CONFIG_FILE: dev.conf
    ports:
      - 8001:80
