version: '3.5'

services:
  frontend:
    build: ./frontend
    image: frontend

  backend:
    build:
      dockerfile: prod.Dockerfile
    env_file:
      - ./.env
    environment:
      - PROD=1

  nginx:
    build: ./nginx
    ports:
      - 8080:80

  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./database:/data/db
