version: '3.5'

services:
  frontend:
    restart: always
    container_name: ${APP_NAME}_frontend

  backend:
    restart: always
    container_name: ${APP_NAME}_backend

  nginx:
    restart: always
    ports:
      - $HOSTPORT:80
    depends_on:
      - frontend
      - backend
    container_name: ${APP_NAME}_nginx

  mongo:
    restart: always
    depends_on:
      - backend
    container_name: ${APP_NAME}_mongo

